### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by dexcell** [donileo/RMessage#12]
It would be nice if we have carthage support. Thank you

**Comment by isadon** [comment]
Will do, will do :).

**Comment by isadon** [comment]
I believe I have Carthage support working. Can you please pull branch 3.0.0 and test integrating RMessage as a framework into your project? Note: It wont exactly be drop in as 3.0.0 has api breaking changes.

**Comment by Mijail** [comment]
For me it doesn't work, it doesn't find a specific .h when importing in a swift project. Seems it is private.
![screen shot 2017-06-20 at 11 23 18](https://user-images.githubusercontent.com/5363842/27326120-e2ba2a54-55aa-11e7-8f5c-10cdda6781c6.png)

![screen shot 2017-06-20 at 11 23 45](https://user-images.githubusercontent.com/5363842/27326149-ff612fd6-55aa-11e7-8ea2-c98b9560e3a2.png)

Moving it to public does make it work but it is not ideal as it should be done each time carthage builds.

EDIT: created  #21

**Comment by isadon** [comment]
@Mijail Thanks. 0e9e4b47161cbfd15d8da283aeeb2425a4c40942 should address this.
