### ISSUE TITLE
Its covering entire screen.

### ISSUE THREAD

**Issue by Rjmaurya13** [donileo/RMessage#14]
RMessagePositionNavBarOverlay showing on entire screen.

**Comment by isadon** [comment]
Can you provide more details on this issue? What kind of device, what kind of orientation? How are you invoking the call to display RMessage? As far as the test project presenting with RMessagePositionNavBarOverlay doesn't show on the entire screen.

**Comment by francis-bware** [comment]
I was having this same issue and was able to solve it by adding a height constraint into setupLayout in  RMessageView.

**Comment by isadon** [comment]
@shmozzle: details on reproducing this issue?

**Comment by francis-bware** [comment]
It was using swift 3. Calling `RMessage.showNotification(in: viewController, title: "title", subtitle:  "subtitle", type: RMessageType.normal, customTypeName: nil, callback: nil)` from a tabbarcontroller

**Comment by isadon** [comment]
Are you seeing this issue directly on a device or the simulator, if so what device? Also were you seeing this all the time (easily reproducible) or intermittently? Can you also pull the latest and see if it still occurs? Trying to to reproduce this issue but not seeing it on my end.

**Comment by francis-bware** [comment]
It was on device. It was happening every time I tried to display one. I'll revert my code back and try and get a screenshot for you in  a little bit.

**Comment by isadon** [comment]
I think its possible this is a bug that was fixed post 2.1.2. When you reproduce this issue on your device can you pull the latest from the master branch and see if you still see the issue?

**Comment by fukemy** [comment]
u can use in appdelegate : self.window.rootViewController.

**Comment by isadon** [comment]
@fukemy Can you provide more details? Are you saying this bug still exists? If so give more details as to how to reproduce exactly.

**Comment by fukemy** [comment]
hello. I just see all question for find my answer that I faced, now it done.
 Also, your lib is great, very thanks u.
