### ISSUE TITLE
Is button title doing anything?

### ISSUE THREAD

**Issue by weibel** [donileo/RMessage#15]
I put in a button title, but no button showed up. 
By looking through RMessageView the button title does not seem to be used. Am I correct?

**Comment by isadon** [comment]
Correct :). Currently RMessage does not support embedding a button even though the methods allow a button title /callback to be passed in just like in the original TSMessages. Passing in those two parameters will do nothing as of now.

I have implemented embedding buttons in the feature branch feature_button but that wont be merged till a future RMessage 3.0.0 considering its an API breaking change. My current implementation asks for the UIButton instance you would like to embed as opposed to having RMessage create the button and set the title via those parameters you see there. This allows you to fully construct your own UIButton with all the settings a button allows you to have as opposed to "just" the title via a parameter you pass in the RMessage presentation calls. Initial drawbacks off the top of my head are that owners of the UIButton instance must be very careful to reference the RMessage sharedInstance strongly in the button callback as that would create a reference cycle.

Take a look at the branch and let me know your thoughts.

**Comment by weibel** [comment]
Thanks for the quick reply. I'll whip something up then.
