### ISSUE TITLE
Which one should I use: RMessage or TSMessages?

### ISSUE THREAD

**Issue by mohakshah** [donileo/RMessage#16]
After looking at [this conversation](https://github.com/KrauseFx/TSMessages/issues/261) I am a little unsure of which repo I should use in my app. I would rather not end up integrating the wrong one in my project only to find out you'll be working on the other. Advice?

**Comment by isadon** [comment]
TSMessages is no longer maintained/supported and RMessage is. RMessage is a fork/rewrite of TSMessages with various improvements and bug fixes. It is recommended you migrate to RMessage but keep in mind version 2.x.x doesnt support integrating UIButtons, that's coming in 3.0.0 which you can test and play with in the 3.0.0 branch.

Please see the README for more info.
