### ISSUE TITLE
How can I display message over application Window

### ISSUE THREAD

**Issue by tobitech** [donileo/RMessage#17]
I'm trying to display a message over the application window but can't except I use "shownotification onViewcontroller" but in my app delegate I can't know the view controller that the app is currently on. I want to use this to display message when user receives notification when app is in foreground

**Comment by isadon** [comment]
For when you want to present on the topmost/current view controller in the window dont use the function calls that ask for a view controller. Those are for when you know which view controller you want to present in. Use the non-viewcontroller presentation calls.
