### ISSUE TITLE
Crash on presentMessageView

### ISSUE THREAD

**Issue by pmagnussen** [donileo/RMessage#18]
We have a crash on presentMessageView that we can't quite wrap our head around.

Here are two screenshots from the stacktrace.

<img width="960" alt="screen shot 2017-04-06 at 12 52 42" src="https://cloud.githubusercontent.com/assets/1857224/24752832/e41b583e-1acf-11e7-95c9-0aee481e7099.png">
<img width="958" alt="screen shot 2017-04-06 at 12 52 27" src="https://cloud.githubusercontent.com/assets/1857224/24752831/e4175536-1acf-11e7-8c5d-6d3c037827e1.png">

Have you experienced this crash before?

**Comment by pmagnussen** [comment]
I branched out and made the change, but I don't have permissions to push.

**Comment by isadon** [comment]
Delegate properties should always (barring special circumstances) be weak so yes this is something that will be fixed. Hopefully that should resolve your crash.

Update: Interestingly enough the reason why its assign (I always make my delegates weak) is because of RMessage having initialized its codebase from TSMessages, TSMessages has it the way it is now, "assign" hmmm...

**Comment by pmagnussen** [comment]
I tried setting it to weak but could still reproduce the crash :/

**Comment by isadon** [comment]
Are you changing your delegate in the middle of presentation or clearing the delegate anywhere. Anything interesting you may be doing in your code? After setting the property to weak can you clear your derived data and rebuild your project? Reset the simulator as well if need be.

**Comment by pmagnussen** [comment]
I haven't found anything particularly interesting yet - still trying to find the exact steps to reproduce the issue. Right now I can only reproduce it semi-randomly.

Could you change it to be a weak reference none the less?

**Comment by pmagnussen** [comment]
I'll try clearing derived data now and see what happens.

**Comment by pmagnussen** [comment]
I think clearing derived data did the trick. I can't seem to reproduce it anymore.

So to sum up: setting the delegate to weak should resolve this issue.

**Comment by isadon** [comment]
Yup. I dont know why the original TSMessages had the property set to assign but there is a very crucial fundamental difference between assign and weak in the instance of a delegate property. When set to assign if the delegate becomes deallocated the property would be pointing to garbage (bad) while when its weak the property becomes nil which is the correct implementation.

**Comment by pmagnussen** [comment]
Thanks for fixing this so quickly.
