### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by AndreyEgorovCSI** [donileo/RMessage#19]
Hi. It seems I found an issue with rotation. Here is a [video](https://www.dropbox.com/s/gmbjqkfr6llrm01/rotationIssue.m4v?dl=0). I just created a new project and add a navigation controller.

**Comment by isadon** [comment]
Yup! Will work on a fix soon :).

**Comment by isadon** [comment]
@AndreyEgorovCSI Please pull the latest master and test, commit f42acf1f1248ff8fbaf62bb651354cf235655cea should fix this issue.

Make sure to call [RMessage interfaceDidRotate] in:
```
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator 
```
in the viewController where rotation is happening. For an example please take a look at the DemoViewController.m code.
