### ISSUE TITLE
update the title of RMessage  (Countdown scenario)

### ISSUE THREAD

**Issue by pkc456** [donileo/RMessage#22]
I want to use RMessage to show countdown. How can I update the text of visible RMessage?

(For e.g.:- In temple run game, while resuming it shows 3..2..1. In similar fashion, I want to use RMessage and update the text)

**Comment by isadon** [comment]
Not sure if you ever resolved this but how about adding a custom UIButton that animates and set endless on the duration type for the message. Button support was just added to the develop branch recently.
