### ISSUE TITLE
issue with UITabBarController

### ISSUE THREAD

**Issue by Vanilil** [donileo/RMessage#23]
I have an issue with the positioning of RMessages in UiTabBarController. 

![simulator screen shot 3 aout 2017 a 08 54 05](https://user-images.githubusercontent.com/6389921/28909806-48054136-782a-11e7-90fd-a35c97fd6b8d.png)

**Comment by isadon** [comment]
Can you give any more details in reproducing this bug? Does it always occur?

**Comment by Vanilil** [comment]
I use this line of code to show RMessage :
<pre> "[RMessage showNotificationWithTitle:NSLocalizedString(@"TITLE_ALERT", @"") subtitle:NSLocalizedString(@"MSG_ALERT", @"") type:RMessageTypeError customTypeName:nil duration:10 callback:nil];" </pre>
It always occur when i tried to show it on an UITabBarController.

**Comment by Vanilil** [comment]
It works better if I use showNotificationInViewController to specify the viewcontroller in which I want to show RMessage.

**Comment by isadon** [comment]
@Vanilil sorry for the wait in responding, been really really busy with some life things :). 

Normally RMessage expects to be presented directly under a UINavigationController. In situations where you may be presenting in some more complex view hierarchies such as when presenting in UITabBarController which is embedded in a UINavigationController you should be explicit and tell RMessage to present specifically  in the UITabBarController via the showNotificationInViewController call as you said. When you do so Rmessage presents correctly. If it gets too tiresome having to pass in the tab bar controller all the time set the default view controller to present in to be the tab bar controller via the + setDefaultViewController class method.

**Comment by Vanilil** [comment]
Ok, Thanks for your answer. I'll tell explicitely which viewController I want.
