### ISSUE TITLE
 [UIColor hx_colorWithHexRGBAString:string alpha:alpha] method not found

### ISSUE THREAD

**Issue by fukemy** [donileo/RMessage#26]
Hello i drop and drag project then got this problem. plz help
![screen shot 2017-10-03 at 14 11 06](https://user-images.githubusercontent.com/8202437/31113730-c9de624c-a844-11e7-8050-f4ed8bda9855.png)

**Comment by fukemy** [comment]
okey it done by use [UIColor colorWithHexString:string alpha:alpha]

**Comment by isadon** [comment]
If you are importing the project manually you must add its dependencies. In the case above you must also add HexColors into your project.
