### ISSUE TITLE
center text and icon

### ISSUE THREAD

**Issue by fukemy** [donileo/RMessage#27]
Hello i need center text and icon, and i can modify height of notification view. plz help me how can i do that 
![screen shot 2017-10-03 at 15 24 33](https://user-images.githubusercontent.com/8202437/31116125-1f7e0144-a84f-11e7-916c-f2b4b11e7e5e.png)

**Comment by isadon** [comment]
@fukemy Please do the following to get the functionality as above:

1. Use the develop branch, the current master branch does not have this new functionality which requires that the title and subtitle labels don't expand to use all the available superview width.
2. Set [[RMessageView appearance] setTitleSubtitleLabelsSizeToFit:YES] in your viewDidLoad (this toggles the functionality mentioned in step 1);
3. When calling RMessage to present pass nil as the subtitle.
4. Use whatever code you normally would use to use your custom checkmark icon as above.

**Comment by fukemy** [comment]
great work! Thanks you
