### ISSUE TITLE
callback after dismiss?

### ISSUE THREAD

**Issue by tspent** [donileo/RMessage#28]
Is it possible to know when the popup is dismissed after the duration? ( Without user tapping)

**Comment by docash59** [comment]
and also when user dismisses the notification from swiping up the notification?

**Comment by isadon** [comment]
Hi, the time RMessage takes to dismiss is as follows:

Time to animate on screen: 0.3s
Time to dismiss after being fully on screen: 1.5s + 0.04 * the height of the message window. This pretty much dictates that longer messages allow the user more time to read them.

@docash59 not sure I understand. If the user swipes up the message is gone.

**Comment by tspent** [comment]
@docash59 When the user is tapping the view, the callback get called. I asking for a callback when the popup is dismissed after the duration expired.

Example -> An error popup animating on the screen and we need some action when the popup is dismissed without user interaction!

In that case the code is calling [dismissWithCallback:nil];

**Comment by isadon** [comment]
@tspent you are correct. I should have a fix up soon.

**Comment by isadon** [comment]
So an update: Whats going on is that the callback block argument is specifically for when the user "taps" on the message. Even then the implementation prior to https://github.com/donileo/RMessage/commit/b04c6a489a17baa5df2a4e1da31c94b82cb9ff05 is that the tap callback gets executed **_after_** the message dismisses as a _result_ of a tap. 

https://github.com/donileo/RMessage/commit/b04c6a489a17baa5df2a4e1da31c94b82cb9ff05 resolves this by making the callback execute on tapping only. It also allows you to pass in a presentingCompletion and dismissalCompletion callback blocks which execute on presentation completion and dismissal completion of the message. These are the callbacks you should use. To get these changes jump on the develop branch.

**Comment by tspent** [comment]
Hey @donileo, is there any plan to release the changes? Don't want to get it from develop branch.

**Comment by isadon** [comment]
There definitely is. The thing is that I want to truly start adding UI/Unit testing to RMessage before I merged the latest develop but haven’t gotten around to the tests. With more people using RMessage and future enhancements testing is becoming a must.

**Comment by tspent** [comment]
Yes, that makes sense. For now though, I will have to fork.
