### ISSUE TITLE
Button on Notifications Not Present

### ISSUE THREAD

**Issue by docash59** [donileo/RMessage#29]
I have just moved over to TSMessage to RMessage and the buttons on the notifications are not visible. I took a look on the example project and yet they aren't present on those either.

Heres my code:
```
[RMessage showNotificationInViewController:self
                                             title:@"Welcome to Version 4.4"
                                          subtitle:@"Would you like to take a read of the release notes?"
                                         iconImage:[UIImage imageNamed:@"iconNotes"]
                                              type:RMessageTypeCustom
                                    customTypeName:@"sdTheme"
                                          duration:RMessageDurationEndless
                                          callback:^{
                                              NSLog(@"Tapped Notification");
                                          }
                                       buttonTitle:@"Read"
                                    buttonCallback:^{
                                        [self showReleaseNotes];
                                    }
                                        atPosition:RMessagePositionTop
                              canBeDismissedByUser:YES];
```
That produces this but no button is visible:
![img_e3241](https://user-images.githubusercontent.com/4446692/33170360-fa0b5c9a-d03f-11e7-8f0f-232fb286d007.JPG)

**Comment by isadon** [comment]
This is expected, as per the README, the button functionality is not enabled unless you are on RMessage 3.x. Yes you can pass a button in in the calls. No it will not work unless on 3.x.

**Comment by isadon** [comment]
@docash59 I added button functionality to the develop branch. Now you can pass in a button via the parameters. Much more customizeable buttons can be passed in via the customizeMessageView delegate function and the setButton call on RMessageView. Please test!

**Comment by docash59** [comment]
That great thank you @donileo!
I will give it a test later.
