### ISSUE TITLE
iOS 11 - (maybe iphoneX) no response

### ISSUE THREAD

**Issue by ycwjjjj** [donileo/RMessage#31]
The customised push can be shown on top while in iPhone 6 plus, 5s, etc. but it is no showing the customised push while in iPhoneX.
While the customised push can be shown while the phone is connecting to Mac with Xcode is compiling. 
The app is detecting push on appdelegate.m inside method didReceiveRemoteNotification:fetchCompletionHandler: for all cases.

Using Xcode 7.3.1. 
RMessage Release 2.1.5
It is strange, can you try to figure it out and resolve it asap. 
:)
Thanks.

**Comment by isadon** [comment]
Can you get on develop? There are various fixes on that branch that may affect whether RMessage displays properly on the X. I tested with develop on the X and though I'd say it doesn't look exactly how I want on the X it does work.

**Comment by ycwjjjj** [comment]
Thanks Donileo for quick reply. 
I will test on the "develop" branch. Since I have to stick to use Xcode 7.3.1 for other needs. Hope the develop version can work. I will get back to you soon.
How about if I use your release 3.0.0? Is it work fine in iPhone X? I will test on it as well. 
Thanks!

**Comment by ycwjjjj** [comment]
I have tested on release 3.0.0 on my app and using Xcode 7.3.1 to build.
Result not OK.
In-app push doesn't show up in iPhone X , another iPhone 6s plus( ios 11) while the in-app push can show up in iphone 5s, 6s plus (both are ios 10).
The strange part is that when this iPhone X is attached to Mac and using Xcode(7.3.1) to run the app in this real device. At the time the phone is still linking to Xcode,  the in-app push can shown up.   
To mention that I did not using CocoaPods to install in my cordova platform since it was failure to install. I added libraries and files manually in to my Xcode's project. 
"develop" version will be tested soon. 
Thanks for your help, Donileo.

**Comment by ycwjjjj** [comment]
Thank you for your support. 
It should not be related to your release and should be the issue in "Capabilities" inside "Target", "background modes" has not been enabled and "Remote notifications" has not be checked in the project in xcode. 
After enabled it, the app can receive push by using didReceiveRemoteNotification:fetchCompletionHandler while in foreground in iOS 11 and your RMessage shown. 
Thank again.

**Comment by isadon** [comment]
Glad you resolved the issue. Yes for the sample project some capabilities may or may not be turned off.
