### ISSUE TITLE
Above Controller

### ISSUE THREAD

**Issue by Bluesky13503** [donileo/RMessage#32]
I find it confusing for people to use it.
The Issue is, that a Notification is displayed onto of the current Content.
This should be a Subview in Navigationbar and pushes the content further down.

If you have a scroll list with Large Title and start to scroll the Large title becomes small and the notification is stuck in the upper part of the screen. 

Wasn't able to solve it myself :(

**Comment by isadon** [comment]
When you say stuck do you mean that you want the notification to scroll up with the scroll list? As far as how RMessage is presented remember originally it began as a fork of TSMessages so thats why its presented the way it is. There may or may not be better ways to do the presentation each with pros/cons. I can definitely look into possible different presentation methods for the future.

Can you post a gif or something that allows me to see the problem?

**Comment by Bluesky13503** [comment]
Do you have an email address i can send it to?

**Comment by isadon** [comment]
I think github allows you to add the files here.

**Comment by Bluesky13503** [comment]
I did a video right of the phone ;) that’s why! I can’t a a video here ;(

**Comment by isadon** [comment]
Oh :). Unfortunately I can't provide a personal email address. Simply upload the video to some public video service and post a link here so that I may see.

**Comment by Bluesky13503** [comment]
![7aec9b1d-26a2-439c-b056-88f8f2efd69e](https://user-images.githubusercontent.com/2928506/34586827-ef54cf0c-f1a5-11e7-86d1-59505905b7c7.png)

**Comment by isadon** [comment]
So can you describe in good detail the actual problem? What is it that occurs exactly?

**Comment by Bluesky13503** [comment]
Check this out

![7b7f7421-0af1-4c7b-93ea-28ee0c3857b4](https://user-images.githubusercontent.com/2928506/34586870-2119158e-f1a6-11e7-97e7-2f95c5367718.jpeg)

**Comment by Bluesky13503** [comment]
Well you have large title from iOS 11 enabled, then notification kicks in, the user start scrolling!
Then this happens.

**Comment by Bluesky13503** [comment]
Check this out....    https://drive.google.com/open?id=1eGbWGnJA60HsR7zCR2u_iB-Q0WOyuhBi

**Comment by isadon** [comment]
Ok yea. I see it. As far as how it presents before the scrolling is that a navigation bar up where the title is? In other words the view right above the notification is a navigation bar? If it is then I'm assuming the initial presentation of the notification is correct as its supposed to present under the nav bar. The position after scrolling would be the issue. If my assumptions are correct about your issue why not simply programmatically call to dismiss the notification as soon as a scroll occurs by the user?

**Comment by Bluesky13503** [comment]
Well, yes the issue is about the behavior when you start scrolling. Well dismissing the notification is a solution. But what happens if the user starts scrolling immediately? 
This would be no good user experience. 
Better would be the the notification would be part of the navigation bar itself.

**Comment by isadon** [comment]
Hmm. I will look further into this.

**Comment by isadon** [comment]
Can you pull the pin_to_navbar branch and tell me if it resolves this issue for you?

**Comment by Bluesky13503** [comment]
Problem Solved with "Pin_to_NavBar" :)

**Comment by isadon** [comment]
Thanks for the bug report. You can go ahead and use develop now as that feature branch will be deleted.
