### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dtomicAZ** [donileo/RMessage#34]
I updated my pods and I get this error:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

as this line 986:
[messageNavigationController.view insertSubview:self belowSubview:messageNavigationController.navigationBar];

I have this in my pod file:
pod 'RMessage', :git => 'https://github.com/donileo/RMessage.git', :branch => 'develop'

I use iPhone 6s, iOS 11.2

**Comment by isadon** [comment]
Are you still getting this error? Sorry for the delay, will look into it soon.

**Comment by dtomicAZ** [comment]
@donileo yes, currently I am using :commit => '7cda71e' which doesn't have this issue.

I forgot to mention, this bug appears second time message want's to show up.

**Comment by isadon** [comment]
Ah ok, yea that little detail should make it easier to debug. As far as the commit you are using is that how far you had to go to not get the crash? In other words two commits before the latest still gives you the crash?

**Comment by dtomicAZ** [comment]
Well, I don't know, I think I tried few commits before newest and still bug was there.

I then compared number of line of version I had before updating pods and found that '7cda71e' was good one.

**Comment by isadon** [comment]
Anything specific about how you are presenting RMessage? Cant seem to duplicate this crash in the example project.

**Comment by dtomicAZ** [comment]
[TestRMessage.zip](https://github.com/donileo/RMessage/files/1680724/TestRMessage.zip)

Here you go, I am sending you example project where crash is happening.

Maybe titleSubtitleLabelsSizeToFit property has something with this bug.

**Comment by isadon** [comment]
Hi,

Thanks for the submission. In the end the issue was mostly due to an existing UIAppearance bug. Commit 2154792c1d62905c1a245980c6c1fcbc0f3358ba on develop fixes this issue. Can you please pull and retest?

Update: aa82d58d5f45d07cb38768321c538f886c23c9f0 also applies to this issue.

**Comment by isadon** [comment]
Any update on this issue is the crash fixed for you?

**Comment by dtomicAZ** [comment]
@donileo Looks good now, thank you for the fix.
