### ISSUE TITLE
prefersStatusBarHidden iPhone X issue

### ISSUE THREAD

**Issue by marcphk** [donileo/RMessage#41]
When setting prefersStatusBarHidden to true on a view controller on the iPhone X, it seems the RMessage notification's height doesn't extend below the notch like it does for VCs with or without navigation bars.

**Comment by isadon** [comment]
Hmm, I’ll check it out.

**Comment by isadon** [comment]
Please pull the latest develop and test. Commit 0ea73a4ad0c492e22c7c70279e26a1ad904aaa00 should fix this.

**Comment by marcphk** [comment]
Fixed - thank you!
