### ISSUE TITLE
Allow RMessage to appear at the bottom of the screen

### ISSUE THREAD

**Issue by robertavram-md** [donileo/RMessage#42]
Currently RMessage is always displayed at the top of the screen. Please update the code to position it at the bottom of the screen as well!

Thank you

**Comment by isadon** [comment]
I’m not sure I understand. RMessage allows showing from the top or bottom though the top is the default if you use a call that doesnt specify a position.

**Comment by isadon** [comment]
Closing issue. Feel free to reopen if RMessage truly doesn't allow to present from the bottom.
