### ISSUE TITLE
blur effect not working in ios 11?

### ISSUE THREAD

**Issue by fukemy** [donileo/RMessage#44]
Hello. After long time i write new project that need to include some notification view, then I used your library, thanks for great code.

 After run app in ios 11. I see the blur effect not working as expect. Plz see my attack  picture to see my problem.
 This image is captured from simulator. Then below is my setting
"warning": {
    "backgroundColor": "#FFCC00",
    "backgroundColorAlpha": 0.3,
    "titleTextColor": "#484638",
    "titleFontSize": 14,
    "subTitleFontSize": 12,
    "subTitleTextColor": "#484638",
    "iconImage": "NotificationBackgroundWarningIcon.png",
    "blurBackground": 1
  },
![simulator screen shot - iphone 5s - 2018-03-30 at 22 30 38](https://user-images.githubusercontent.com/8202437/38143386-76e9710a-346a-11e8-8801-f95552d97bb0.png)

**Comment by isadon** [comment]
Can you try a different background color like red to test and see if the blurring is working?

**Comment by fukemy** [comment]
Hi. Here is image with red color
![simulator screen shot - iphone 5s - 2018-03-31 at 11 04 19](https://user-images.githubusercontent.com/8202437/38159480-599d176e-34d3-11e8-90c6-1de3e657b003.png)
Here is my config:
"warning": {
    "backgroundColor": "#FF0000",
    "backgroundColorAlpha": 0.9,
    "titleTextColor": "#484638",
    "titleFontSize": 14,
    "subTitleFontSize": 12,
    "subTitleTextColor": "#484638",
    "iconImage": "NotificationBackgroundWarningIcon.png",
    "blurBackground": 1
  }

**Comment by isadon** [comment]
Hmm.. Its actually working fine for me in the simulator at least with iOS 11.3. Are you sure you are running iOS 11? Can you verify your deployment target and runtime of the simulator is greater than or equal to iOS 8? If possible can you send me a sample Xcode Project so that I can test the functionality?

**Comment by isadon** [comment]
Any update on this? Since I can't reproduce the problem can you answer the following:

What is your XCode deployment target?
Does the issue occur on Device or Simulator?
What version of iOS is running on the device or simulator?

**Comment by fukemy** [comment]
Hello. I am stucking at other problem. So can read your post. I update 2 image about this problem
 First: alpha 0.6 blur 1
 Second : alpha 1 blur 1
"warning": {
    "backgroundColor": "#FFCC00",
    "backgroundColorAlpha": 1,
    "titleTextColor": "#484638",
    "titleFontSize": 14,
    "subTitleFontSize": 12,
    "subTitleTextColor": "#484638",
    "iconImage": "NotificationBackgroundWarningIcon.png",
    "blurBackground": 1
  },

 Then nothing difference. Plz see my attack pictures. Tested on Iphone 5s IOS 11.2.2,XCode Version 9.2 (9C40b)
![alpha 0 6 blur true](https://user-images.githubusercontent.com/8202437/38453090-2e966abe-3a7a-11e8-86a8-7d732e687da4.png)
![alpha 1 blue true](https://user-images.githubusercontent.com/8202437/38453091-2edac6b4-3a7a-11e8-98ff-146451b9ec05.png)

**Comment by isadon** [comment]
Unfortunately I can't reproduce. I tested on a iPhone 8 Plus and the simulator.

**Comment by fukemy** [comment]
my solution is got notification and show notification based on self.window.rootView. Im trying to get rootViewController of stack and test

**Comment by isadon** [comment]
Can you send me an example project containing the problem?

**Comment by fukemy** [comment]
Hi. After I changed  to show Rmessage i topViewController like presented Viewcontroller. It working, show in self.window.rootView not working. It's my fault, sorry.
