### ISSUE TITLE
How to add attributedString in the subtitle?

### ISSUE THREAD

**Issue by Chemprogrammer** [donileo/RMessage#45]
It is a great work! Can I add some attributedString in the subtitle?

**Comment by isadon** [comment]
The 3.0 branch allows you too but unfortunately it is a bit out of sync with the main master branch in terms of bug fixes right now due to the branches diverging. I plan on resolving that problem sometime soon.

**Comment by isadon** [comment]
Attributed string support is coming very soon I believe. RMessage has been rewritten in Swift for 3.0.0.

**Comment by isadon** [comment]
Closing this issue, support for attributed strings can now be done by customizing the passed in RMessageSpec before displaying a message.
