### ISSUE TITLE
Set icon color in custom designs JSON

### ISSUE THREAD

**Issue by harrytutorful** [donileo/RMessage#46]
Hi there, 

Is it possible to set the tint color for the icon inside of AlternativeDesigns.json? 

I have checked the guide and it isn't there, but is it possible to do so without creating multiple coloured image sets? Would just be a good space saver for me because I use differently colored icons multiple times throughout my app.

Thanks!

**Comment by isadon** [comment]
Will definitely look into this. Good idea!

Update: A quick look into this suggests to me that when enabling the feature in the alternative designs json the tint color will only apply to template images. So even if you have the feature enabled normal images (none-template) will be unaffected. Does that sound like what you'd expect?

**Comment by isadon** [comment]
Commit 50cf0fea8a3ab50e29142f9e01cc0f78b0e3e3c9 should fix this issue. Please test and let me know of any issues. Make sure to set any icon images you want to "tint" to be template images in Xcode and then use "iconImageTintColor" property in your json file.

**Comment by harrytutorful** [comment]
That's perfect, thank you so much! It seems to work perfectly from what I've tested 🥇

**Comment by harrytutorful** [comment]
Also with regards to your update on your original comment, that is expected behaviour in my eyes, I only template images I want to tint, otherwise I probably want the original image because it has some special effects that need to be retained.

**Comment by isadon** [comment]
Makes sense. I stated the functionality mainly as a form of documentation for other users. Closing issue..
