### ISSUE TITLE
RMessagePositionTop displaying not correctly when double height status bar

### ISSUE THREAD

**Issue by sssandyad** [donileo/RMessage#47]
Can I do something about this? I want to correctly display RMessage below Navigation Bar when double height status bar occurs

![simulator_screen_shot_-_iphone_4s_ios_9 3_-_2018-01-15_at_18 13 38](https://user-images.githubusercontent.com/6153272/38968545-1dcfa624-43b6-11e8-8e43-649a4459b0db.png)

**Comment by isadon** [comment]
Probably not, But I can! :). Give me a bit of time to see If I can issue a fix. Kinda busy today so most likely tomorrow.

**Comment by sssandyad** [comment]
thank you. I will wait for the good news from you @donileo :)

**Comment by isadon** [comment]
@sssandyad Can you give more details on how to reproduce this issue. In the simulator I select Hardware-> Toggle In Call Status Bar to reproduce what you see above but RMessage displays fine under multiple scenarios.

**Comment by sssandyad** [comment]
I created a new blank project to reproduce this issue. Please try the scenario when using UITabBarController @donileo 
![screen shot 2018-04-26 at 17 02 21](https://user-images.githubusercontent.com/6153272/39300363-9e9e90a2-4975-11e8-8081-98f1f3f7cecf.png)

I put the testing project in this repo:
https://github.com/sssandyad/testRMessage

**Comment by sssandyad** [comment]
looks like this issue has been solved in version `2.3.0` :)
