### ISSUE TITLE
Typo in your README.md

### ISSUE THREAD

**Issue by Slessi** [donileo/RMessage#5]
In your second example

``` objective-c
   title:@"Update available"
subtitle:@"Please update the app"
   image:nil
```

`image` needs to become `iconImage`

Also in your `[RMessageView appearance]` example

``` objective-c
[[RMessageView appearance] setContentFont:[UIFont boldSystemFontOfSize:10]];
[[RMessageView appearance] setContentTextColor:[UIColor greenColor]];
```

needs to become

``` objective-c
[[RMessageView appearance] setSubtitleFont:[UIFont boldSystemFontOfSize:10]];
[[RMessageView appearance] setSubtitleTextColor:[UIColor greenColor]];
```

**Comment by isadon** [comment]
Fixed. For the second example, a UIImage was provided since no support for buttons is yet included but will be coming soon.

**Comment by Slessi** [comment]
Not sure if I misunderstood or if you misunderstood, but readme references the label as `image:` but if you look at [RMessage.h:131](https://github.com/donileo/RMessage/blob/056e24c1d435bf17c96d47e024e406b79f004b07/RMessage/RMessage.h#L131) you will see the label written as `iconImage:`

**Comment by isadon** [comment]
Oh :). No problem.. Thanks for catching that.. The README does need to keep up a bit better with the library, I'll try to take some time to check it better for any other errors and in the future. Will make this fix now.
