### ISSUE TITLE
How to reset all queued messages and the displayed view?

### ISSUE THREAD

**Issue by shaofuku** [donileo/RMessage#50]
Hello, there!

I have some queued messages and a displayed notification. Is it possible to reset all and then just show a new notification without dismiss for each messages I don't want?

**Comment by isadon** [comment]
Not currently unfortunately but I have thought of this as an added feature :). Would definitely be a great feature. Any suggestions for how you expect it should work? Maybe a dismiss all button on all notifications when there are multiple in the queue?

**Comment by shaofuku** [comment]
@donileo  Thanks for your reply.

My scenario is when a monitoring status changed, I can clear all the messages about old state 
and dismiss the displayed view programmatically. Then re-send notifications about new state without showing the out of date messages.

**Comment by isadon** [comment]
Hi @shaofuku Please try the new version of RMessage, which allows cancellation of queued messages.
