### ISSUE TITLE
notification showing several times

### ISSUE THREAD

**Issue by jeromeMorjon** [donileo/RMessage#51]
Hello,
Is it normal when a use the following code:

```
[RMessage showNotificationWithTitle:@"title"
                               subtitle:textToDisplay
                                   type:RMessageTypeError
                         customTypeName:nil
                               callback:nil];
```

it show multiple times. I call it in a notification observer and the code is called 2, 3 or 4 times instead of one...
Why ? 

Thank you

**Comment by isadon** [comment]
No it is not normal. Set a breakpoint where you are calling it to see why your notification method is being called multiple times. Most likely that is where the problem lies.

**Comment by jeromeMorjon** [comment]
Ok.

When I put a breakpoint, i have the following thread list : 

- method where I show the banner 
- postnotification
- completionhandler
- network request
- method
- action 

In the last stack trace i don't know why it show multiple times the method. 
If i remove the show method, the problem does not happen again

**Comment by isadon** [comment]
Again, you have to debug why your method is being called multiple times. If the method where RMessage is called to show is being called multiple times then obviously it will do exactly that. You have to be careful where you tell RMessage to show as that method may be called multiple times by Apple's frameworks and its perfectly fine for that to happen.

**Comment by isadon** [comment]
Closing, if you can show that it is truly RMessage at fault of showing multiple times feel free to reopen.
