### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dalein** [donileo/RMessage#55]
I'm using RMessage (2.3.2).
I have a crash on line 508 in RMessageView.m with message:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSLayoutConstraint for <UIView: 0x133d56730; frame = (47 10; 343.333 50.6667); autoresize = RM+BM; layer = <CALayer: 0x283758de0>>: Constraint items must each be a view or layout guide.'`

Call Rmessage like that:

`[RMessage showNotificationInViewController:vc
title:title
subtitle:subTitle
iconImage:nil
type:RMessageTypeError
customTypeName:nil
duration:duration
callback:callback
buttonTitle:nil
buttonCallback:nil
atPosition:RMessagePositionTop
canBeDismissedByUser:YES];`

iOS 12

**Comment by Dalein** [comment]
It was because of custom layoutGuide in vc

**Comment by isadon** [comment]
Is RMessage still to blame for the issue though? If so can you post the project to reproduce the issue?

**Comment by Dalein** [comment]
no, I think it can be closed. Sorry for disturbing
