### ISSUE TITLE
Infinite loop when using automatic presentationViewController detection

### ISSUE THREAD

**Issue by dominicfreeston** [donileo/RMessage#57]
There's the risk of an infinite loop when using the automatic presentationViewController detection from a modal, like this: NavigationController -> Modal (via visibleViewController) -> NavigationController (via presentingViewController) -> etc

Creating this issue because I think useful for others to know about when evaluating the library, but potential fix is available in #56

**Comment by isadon** [comment]
Thanks. Will get on the ball about this hopefully from today to this weekend. Sorry for the long wait..

**Comment by isadon** [comment]
Commit 65b4db2 has been pushed to develop to fix this issue. Testing would be appreciated.

**Comment by dominicfreeston** [comment]
It's essentially the same thing and the tests were updated the same way, so I don't doubt it's fine
