### ISSUE TITLE
Demo project doesn't compile; downloaded as zip file

### ISSUE THREAD

**Issue by zulfishah** [donileo/RMessage#63]
Hi,
I downloaded the RMessage zip file for the project. When I try to compile the demo project in Xcode, I get the following error:

> Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.2 compiler: /Users/zulfishah/Downloads/RMessage-master/Carthage/Build/iOS/HexColors.framework/Modules/HexColors.swiftmodule/x86_64.swiftmodule

Is there a work-around for this?
Thanks.

**Comment by isadon** [comment]
Can you please retry with the latest develop?

**Comment by zulfishah** [comment]
It works with the latest 'develop' branch. Thanks!
