### ISSUE TITLE
Crashing the app in iOS 13.

### ISSUE THREAD

**Issue by kishor010** [donileo/RMessage#65]
In all the simulator and iOS 13 devices..
App is getting crashed says "nil" cannot insert (object) at index ......
I can not debug in simulator at all.
```
+ (void)prepareNotificationForPresentation:(RMessageView *)messageView
{
  [mLock lock];
        [[RMessage sharedMessage].messages addObject:messageView];
  [mLock unlock];

  [nLock lock];
  if (![RMessage sharedMessage].notificationActive) {
    [nLock unlock];
    [[RMessage sharedMessage] presentMessageView];
    return;
  }
  [nLock unlock];
}
```

**Comment by isadon** [comment]
Which line is the crash at?

**Comment by kishor010** [comment]
> Which line is the crash at?

At line no. 4
[[RMessage sharedMessage].messages addObject:messageView];
I checked In few of the iOS devices it is being crashed.

**Comment by isadon** [comment]
Really won't be able to investigate for now but you can try to debug why messageView is nil which it shouldn't be. I would put a breakpoint at line 4 and start tracing the stack trace upwards.
