### ISSUE TITLE
Allow customize height of MessageView

### ISSUE THREAD

**Issue by 9you** [donileo/RMessage#8]
I'm using RMessage with just title, no subtitle, no icon, etc. But the default MessageView size too big for just one line of text. Can you provide any way to alter constraint constant or something similarly to change the height of MessageView?

Thank you very much.

**Comment by isadon** [comment]
Noted.

**Comment by isadon** [comment]
@9you Can you retest this issue on the latest HEAD. Think it should be good now. Only thing I'm noticing is the actual title label is always left aligned. In messages with a title and subtitle left align seems perfect. For singular messages (no subtitle) it would be nice to allow for center aligning it + right aligning it 🙄 .

**Comment by 9you** [comment]
@donileo Thank you very much. It seem nearly perfect. 👍 

![screen shot 2017-02-16 at 11 43 22 am](https://cloud.githubusercontent.com/assets/16769449/23010427/f9cfae9e-f44d-11e6-91d5-afa49ba7b76c.png)

**Comment by isadon** [comment]
Closing issue. Will provide more details down the line if some more customization options for the specific size of RMessage are provided.
